spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

logging:
  level:
    com.scalekit: INFO
    org.springframework.web: WARN
