apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scalekit-ingress
  namespace: scalekit
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - scalekit.app
      secretName: scalekit-tls  # Created automatically by cert-manager
  rules:
    - host: scalekit.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scalekit-service
                port:
                  number: 80
