package com.scalekit.cache.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Report generated by {@code ConsistentHashRing.detectHotspots} describing a node's load.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class HotspotReport {
    /** Name of the node */
    private String nodeName;
    /** Actual number of lookups performed on this node */
    private long actualLookups;
    /** Expected average lookups for a balanced node */
    private double expectedLookups;
    /** Load factor = actual / expected */
    private double loadFactor;
    /** Whether this node is considered a hotspot */
    private boolean isHotspot;
    /** Recommendation for mitigation */
    private String recommendation;
}
